/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
 * Generated on: 19-Jun-2020 14:47:21
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s33,30 -> [-4 4)
 *   Product         : s31,30 -> [-1 1)
 *   Accumulator     : s33,30 -> [-4 4)
 *   Round Mode      : convergent
 *   Overflow Mode   : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
const int BL = 64;
const int16_T B[64] = {
       -5,     -4,      8,     14,     -9,    -34,     -2,     63,     40,
      -88,   -115,     81,    228,     -7,   -353,   -172,    435,    475,
     -389,   -879,    111,   1307,    504,  -1610,  -1547,   1558,   3139,
     -753,  -5695,  -2028,  12330,  26166,  26166,  12330,  -2028,  -5695,
     -753,   3139,   1558,  -1547,  -1610,    504,   1307,    111,   -879,
     -389,    475,    435,   -172,   -353,     -7,    228,     81,   -115,
      -88,     40,     63,     -2,    -34,     -9,     14,      8,     -4,
       -5
};
